### PR TITLE
added material for Sundays tutorial/practical - QSRs survey paper

### PR DESCRIPTION
**Pull request by gatsoulis**
Hopefully pre-read.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
It might be better to put this on the wiki. Not in here. Do you want me to move it (and link it)?

**Comment by gatsoulis** [comment]
Sure, please place the material where you feel most appropriate.

**Comment by marc-hanheide** [comment]
See here: https://github.com/strands-project/lamor15/wiki/Tutorial-materials-4#references

**Comment by gatsoulis** [comment]
Thanks.

**Pull request closed without merging**
